### ISSUE TITLE
Unknown CMake command "hip_add_library".

### ISSUE THREAD

**Issue by wangzhihan-scut** [hpc-app/gromacs-rocm-2.1.96#2]
I'm compling this project in docker.
ROCm:  2.3.14
os version: Ubuntu-16.04
I can't find any tutorial about gromacs-rocm, so I follow the Gromacs officail tutorial. About fft library, I choose the FFTW3 which is intalled under  "/opt/fftw-3.3.8".
Here is my installation command:
```
cd  gromacs-rocm-2.1.96
mkdir build
cd build
cmake .. -DGMX_GPU=ON -DCMAKE_INSTALL_PREFIX=/opt/gromacs/rocm-2.1.96 -DHIP_TOOLKIT_ROOT_DIR=/opt/rocm/hip  -DGMX_FFT_LIBRARY=fftw3 -DFFTWF_LIBRARY=/opt/fftw-3.3.8/lib/libfftw3f.so -DFFTWF_INCLUDE_DIR="/opt/fftw-3.3.8/include" 2>&1 |tee cm.log
```

Then errors occurred, it says "Unknown CMake command hip_add_library" at src/gromacs/CMakeLists.txt:195. I want to know whether this project can run on Rocm for AMD GPU? And here is the error log file.
[cm.log](https://github.com/hpc-app/gromacs-rocm-2.1.96/files/3625131/cm.log)

**Comment by wangzhihan-scut** [comment]
@yuzhou-zhang Do you have any suggestions?

**Comment by yuzhou-zhang** [comment]
Please clone the https://github.com/hpc-app/gromacs-rocm-2.5.27.git repository. That project should run if built correctly. For the hip_add_library problem, I think you need to copy the FindHIP directory and the  FindHIP.cmake file from your hip install directory (usually in /opt/rocm/hip/cmake by default) to the cmake directory in the gromacs unzip directory. Please note that the hipified gromacs need hip that support 12 bytes float3. As far as I know, the hip released in rocm still doesn't support that feature until rocm-2.5. You can print the size of a float3 variable in a C code that is compiled using hipcc to test if  the float3 in your hip is 12 bytes or 16 bytes. If it's 16 bytes, you need to clone a newer version of hip from https://github.com/ROCm-Developer-Tools/HIP.git and install it and use it to compile the hipified gromacs.

**Comment by yuzhou-zhang** [comment]
@wangzhihan-scut
